### ISSUE TITLE
Outdated example

### ISSUE THREAD

**Issue by dschnare** [buildkite/nodejs-docker-example#1]
Isn't the `pipeline.yml` file outdated? Shouldn't it be:

```yml
steps:
  - name: ":node:"
    command: "npm test"
    plugins:
      docker-compose#v2.1.0:
        run: app
```
